version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Packages started on `date`
      - npm install
      - echo Test started on `date`
      - CI=true npm test
  build:
    commands:
      - echo Build started on `date`
      - npm run-script build 
artifacts:
  files:
    - 'build/**/*'
    - appspec.yml